/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.dao.AvaliacaoDao;
import model.dto.AvaliacaoDTO;

/**
 *
 * @author Felipe V
 */
public class TelaAvaliacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAvaliacao
     */
    public TelaAvaliacao() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloAvaliacao = new javax.swing.JLabel();
        jLabelDataAplicacao = new javax.swing.JLabel();
        jLabelEspecificacaoAvaliacao = new javax.swing.JLabel();
        jTextFieldEspecificacao = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltaAoMenu = new javax.swing.JButton();
        jLabelNotaAvaliacao = new javax.swing.JLabel();
        TxtFieldNota = new javax.swing.JTextField();
        jLabel1Aprovado = new javax.swing.JLabel();
        jCheckBoxAprovadoSim = new javax.swing.JCheckBox();
        jCheckBoxAprovadoNao = new javax.swing.JCheckBox();
        jFormattedTextFieldDataAplicacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloAvaliacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTituloAvaliacao.setForeground(new java.awt.Color(30, 163, 163));
        jLabelTituloAvaliacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAvaliacao.setText("AVALIAÇÕES");

        jLabelDataAplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDataAplicacao.setForeground(new java.awt.Color(30, 163, 163));
        jLabelDataAplicacao.setText("Data de Aplicação:");

        jLabelEspecificacaoAvaliacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEspecificacaoAvaliacao.setForeground(new java.awt.Color(30, 163, 163));
        jLabelEspecificacaoAvaliacao.setText("Especificação:");

        jTextFieldEspecificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEspecificacaoActionPerformed(evt);
            }
        });

        jButtonConsultar.setBackground(new java.awt.Color(30, 163, 163));
        jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonInserir.setBackground(new java.awt.Color(30, 112, 112));
        jButtonInserir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInserir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(30, 112, 112));
        jButtonAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(30, 112, 112));
        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonVoltaAoMenu.setBackground(new java.awt.Color(28, 68, 135));
        jButtonVoltaAoMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVoltaAoMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltaAoMenu.setText("Menu");
        jButtonVoltaAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltaAoMenuActionPerformed(evt);
            }
        });

        jLabelNotaAvaliacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNotaAvaliacao.setForeground(new java.awt.Color(30, 163, 163));
        jLabelNotaAvaliacao.setText("Nota:");

        TxtFieldNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNotaActionPerformed(evt);
            }
        });

        jLabel1Aprovado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Aprovado.setForeground(new java.awt.Color(30, 163, 163));
        jLabel1Aprovado.setText("Aprovado:");

        jCheckBoxAprovadoSim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxAprovadoSim.setForeground(new java.awt.Color(30, 163, 163));
        jCheckBoxAprovadoSim.setText("Sim");
        jCheckBoxAprovadoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAprovadoSimActionPerformed(evt);
            }
        });

        jCheckBoxAprovadoNao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxAprovadoNao.setForeground(new java.awt.Color(30, 163, 163));
        jCheckBoxAprovadoNao.setText("Não");
        jCheckBoxAprovadoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAprovadoNaoActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataAplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataAplicacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTituloAvaliacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDataAplicacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelEspecificacaoAvaliacao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1Aprovado)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxAprovadoSim)
                        .addGap(20, 20, 20)
                        .addComponent(jCheckBoxAprovadoNao))
                    .addComponent(jLabelNotaAvaliacao)
                    .addComponent(jButtonVoltaAoMenu)
                    .addComponent(TxtFieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEspecificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButtonVoltaAoMenu)
                .addGap(18, 18, 18)
                .addComponent(jLabelTituloAvaliacao)
                .addGap(26, 26, 26)
                .addComponent(jLabelEspecificacaoAvaliacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEspecificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataAplicacao)
                    .addComponent(jFormattedTextFieldDataAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelNotaAvaliacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtFieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Aprovado)
                    .addComponent(jCheckBoxAprovadoSim)
                    .addComponent(jCheckBoxAprovadoNao))
                .addGap(19, 19, 19)
                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEspecificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEspecificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEspecificacaoActionPerformed

    private void jCheckBoxAprovadoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAprovadoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAprovadoSimActionPerformed

    private void jButtonVoltaAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltaAoMenuActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVoltaAoMenuActionPerformed

    private void TxtFieldNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNotaActionPerformed

    private void jCheckBoxAprovadoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAprovadoNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAprovadoNaoActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        TelaConsultaAvaliacao telaConsultaAvaliacao = new TelaConsultaAvaliacao();
        this.dispose();
        telaConsultaAvaliacao.setVisible(true);
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        String especificacao, data, nota, situacao1, situacao2;
        
        especificacao = jTextFieldEspecificacao.getText();
        data = jFormattedTextFieldDataAplicacao.getText();
        nota = TxtFieldNota.getText();
        situacao1 = jTextFieldEspecificacao.getText();
        situacao2 = jCheckBoxAprovadoNao.getText();

        AvaliacaoDTO avaliacaoDto = new AvaliacaoDTO();
        avaliacaoDto.setEspecificacao(especificacao);
        avaliacaoDto.setData(data);
        avaliacaoDto.setNota(nota);
        avaliacaoDto.setSituacao1(situacao1);
        avaliacaoDto.setSituacao2(situacao2);
        
        AvaliacaoDao avaliacaoDao = new AvaliacaoDao();
        avaliacaoDao.create(avaliacaoDto);
        
        
        
        
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        String especificacao, data, nota, aprovado, id;
        
        id = jTextFieldEspecificacao.getText();
        especificacao = JOptionPane.showInputDialog(null,"Digite a nova especificação: ");
        data = JOptionPane.showInputDialog(null,"Digite a nova data: ");
        nota = JOptionPane.showInputDialog(null,"Digite a nova nota: ");
        
        AvaliacaoDTO avaliacaoDto = new AvaliacaoDTO();
        avaliacaoDto.setEspecificacao(especificacao);
        avaliacaoDto.setData(data);
        avaliacaoDto.setNota(nota);
        
        AvaliacaoDao avaliacaoDao = new AvaliacaoDao();
        avaliacaoDao.update(avaliacaoDto);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jFormattedTextFieldDataAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataAplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataAplicacaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFieldNota;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonVoltaAoMenu;
    private javax.swing.JCheckBox jCheckBoxAprovadoNao;
    private javax.swing.JCheckBox jCheckBoxAprovadoSim;
    private javax.swing.JTextField jFormattedTextFieldDataAplicacao;
    private javax.swing.JLabel jLabel1Aprovado;
    private javax.swing.JLabel jLabelDataAplicacao;
    private javax.swing.JLabel jLabelEspecificacaoAvaliacao;
    private javax.swing.JLabel jLabelNotaAvaliacao;
    private javax.swing.JLabel jLabelTituloAvaliacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEspecificacao;
    // End of variables declaration//GEN-END:variables
}
