/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Avaliacao;
import model.dao.AvaliacaoDao;

/**
 *
 * @author Felipe V
 */
public class TelaConsultaAvaliacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaAvaliacao
     */
    public TelaConsultaAvaliacao() {
        initComponents();
        DefaultTableModel consultaAvaliacoes = (DefaultTableModel) tabelaConsultaAvaliacao.getModel();
        tabelaConsultaAvaliacao.setRowSorter(new TableRowSorter(consultaAvaliacoes));

        readTelaConsultaAvaliacao();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultaAvaliacao = new javax.swing.JTable();
        pesquisarAvaliacao = new javax.swing.JButton();
        consultarAvaliacao = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 163, 163));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR AVALIAÇÃO");

        tabelaConsultaAvaliacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Avaliação", "Data Aplicação", "Nota", "Aprovado", "Especificação", "ID Professor", "ID Aluno", "ID Matéria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaConsultaAvaliacao);

        pesquisarAvaliacao.setBackground(new java.awt.Color(30, 163, 163));
        pesquisarAvaliacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesquisarAvaliacao.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarAvaliacao.setText("Buscar");
        pesquisarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAvaliacaoActionPerformed(evt);
            }
        });

        consultarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAvaliacaoActionPerformed(evt);
            }
        });

        jButtonVoltar.setBackground(new java.awt.Color(28, 68, 135));
        jButtonVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(consultarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(pesquisarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(consultarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesquisarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaAvaliacao telaAvaliacao = new TelaAvaliacao();
        this.dispose();
        telaAvaliacao.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void consultarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarAvaliacaoActionPerformed

    private void pesquisarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAvaliacaoActionPerformed
        readAvaliacoesConsult(consultarAvaliacao.getText());
    }//GEN-LAST:event_pesquisarAvaliacaoActionPerformed

        public void readAvaliacoesConsult(String data_avaliacao){
        DefaultTableModel consultaAvaliacoes = (DefaultTableModel) tabelaConsultaAvaliacao.getModel();
        consultaAvaliacoes.setNumRows(0);
        AvaliacaoDao alunoDao = new AvaliacaoDao();

        for(Avaliacao avaliacao: alunoDao.readAvaliacoesConsult(data_avaliacao)){

            consultaAvaliacoes.addRow(new Object[]{
                avaliacao.getId_avaliacao(),
                avaliacao.getData_aplicacao(),
                avaliacao.getNota_avaliacao(),
                avaliacao.isAprovado(),
                avaliacao.getEspecificacao(), 
                avaliacao.getId_professor(),
                avaliacao.getId_aluno(),
                avaliacao.getId_materia()

            });
        }      
    }
    
    public void readTelaConsultaAvaliacao(){
        DefaultTableModel consultaAvaliacoes = (DefaultTableModel) tabelaConsultaAvaliacao.getModel();
        consultaAvaliacoes.setNumRows(0);
        AvaliacaoDao avaliacaoDao = new AvaliacaoDao();

        for(Avaliacao avaliacao: avaliacaoDao.read()){

            consultaAvaliacoes.addRow(new Object[]{
                avaliacao.getId_avaliacao(),
                avaliacao.getData_aplicacao(),
                avaliacao.getNota_avaliacao(),
                avaliacao.isAprovado(),
                avaliacao.getEspecificacao(), 
                avaliacao.getId_professor(),
                avaliacao.getId_aluno(),
                avaliacao.getId_materia()

            });
        }


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField consultarAvaliacao;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisarAvaliacao;
    private javax.swing.JTable tabelaConsultaAvaliacao;
    // End of variables declaration//GEN-END:variables
}
